---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r}
### AS3

install.packages('plyr', repos = "http://cran.us.r-project.org")
options(repos = list(CRAN="http://cran.rstudio.com/"))
require(plyr)

# 1) Import the csv file into R and present the descriptive statistics of the numerical variables as well as the categorical variables in the dataset.
bs <- read.csv(file = "banksalary.csv")

# Convert the Salary variable into numeric:
bs$Salary <- gsub("[,$]", "", bs$Salary)
bs$Salary <- as.numeric(bs$Salary)

summary(bs)
```

```{r}
# 2) A plaintiff’s lawyer claims that there is a significant difference in average salary between female employees and male employees. As an analyst for the plaintiff, how would you support this claim? Use a t-test and explain the results as well as your interpretation.

# First, let's check the normality and variances within the Gender variable:
require(data.table)
bs <- data.table(bs)

# Normality test:
bs[, shapiro.test(Salary), Gender] # p-values are close to 0, the distribution is probably not normal.

# So, we shall use an Ansari-Bradley Test for the equality of variances:
ansari.test(Salary ~ Gender, bs)  # The p-value is very small, indicating that the variances are probably not equal.

t.test(Salary ~ Gender, data = bs, var.equal = FALSE)

# The p-value is close to zero, therefore, we can reject the H_0 and confirm the lawyer's claims. There is a significant difference in average salary between males and females.
```

```{r}
# 3) Transform EducLev into several dummy variables. The number of dummy variables you create will depend on your logical judgment. Also transform JobGrade, Gender, and PCJob into dummy variables.
install.packages("fastDummies")
require(fastDummies)

bs <- dummy_cols(bs, select_columns = c("EducLev", "JobGrade", "Gender", "PCJob"), remove_first_dummy = TRUE)
head(bs)
```

```{r}
# 4) The defense counsel tries to counter against the plaintiff's argument by showing that the mean difference between the two groups is biased because he or she did not control for several other factors/variables. Estimate a multiple regression model to strengthen/bolster the plaintiff's justification, then write a report explaining your results.
# - Also discuss about: what R-squared is and what it means, what the meaning of the t-values and the coefficients are (or estimates).
reg <- lm(Salary ~ YrsExper + Age + YrsPrior + EducLev_2 + EducLev_3 + EducLev_4 + EducLev_5 + JobGrade_2 + JobGrade_3 + JobGrade_4 + JobGrade_5 + JobGrade_6 + Gender_Male + PCJob_Yes, data = bs)

install.packages("stargazer")
require(stargazer)

stargazer(reg, type = "text")
```

```{r}
# 5) Do these data provide evidence that there is discrimination against female employees in terms of salary?

# Yes, males earn 2,554.47 more than female on average, other conditions being equal. So, there is definitely an evidence that there is a discrimination against female employees in terms of salary.
```

```{r}
### Extra credit
# You may get more interesting results to talk about by including interaction terms in your regression model. Explain what an interaction term is, how we can estimate a regression model with interaction terms and how we could interpret the results.

inter <- lm(Salary ~ YrsExper + Age + YrsPrior + EducLev_2 + EducLev_3 + EducLev_4 + EducLev_5 + JobGrade_2 + JobGrade_3 + JobGrade_4 + JobGrade_5 + JobGrade_6 + Gender_Male + PCJob_Yes + Gender_Male * Age, data = bs)

stargazer(inter, type = "text")
```
